#!/usr/bin/with-contenv bash

# Create required folders
mkdir -p /tmp/nginx/body \
	/run/nginx \
	/var/log/nginx \
	/data/nginx \
	/data/custom_ssl \
	/data/access \
	/data/nginx/default_host \
	/data/nginx/default_www \
	/data/nginx/proxy_host \
	/data/nginx/redirection_host \
	/data/nginx/stream \
	/data/nginx/dead_host \
	/data/nginx/temp \
	/data/nginx/custom \
	/var/lib/nginx/cache/public \
	/var/lib/nginx/cache/private \
	/var/cache/nginx/proxy_temp

rm -rf /data/logs
find /data/nginx/ -type f -name '*.conf' -exec sed -i "s|include conf.d/include/assets.conf;||g" {} \;
find /data/nginx/ -type f -name '*.conf' -exec sed -i "s/# Asset Caching//g" {} \;
find /data/nginx/ -type f -name '*.conf' -exec sed -i "s/proxy_http_version.*//g" {} \;
find /data/nginx/ -type f -name '*.conf' -exec sed -i "s/access_log.*//g" {} \;
find /data/nginx/ -type f -name '*.conf' -exec sed -i "s/error_log.*//g" {} \;

touch /data/nginx/error.log && chmod 777 /data/nginx/error.log && chmod -R 777 /var/cache/nginx
chown root /tmp/nginx

# Dynamically generate resolvers file, if resolver is IPv6, enclose in `[]`
# thanks @tfmm
#if [ "$DISABLE_IPV6" == "true" ] || [ "$DISABLE_IPV6" == "on" ] || [ "$DISABLE_IPV6" == "1" ] || [ "$DISABLE_IPV6" == "yes" ];
#then
#  echo resolver "$(awk 'BEGIN{ORS=" "} $1=="nameserver" { sub(/%.*$/,"",$2); print ($2 ~ ":")? "["$2"]": $2}' /etc/resolv.conf) ipv6=off valid=10s;" > /usr/local/nginx/conf/conf.d/include/resolvers.conf
#else
#  echo resolver "$(awk 'BEGIN{ORS=" "} $1=="nameserver" { sub(/%.*$/,"",$2); print ($2 ~ ":")? "["$2"]": $2}' /etc/resolv.conf) valid=10s;" > /usr/local/nginx/conf/conf.d/include/resolvers.conf
#fi

# Generate dummy self-signed certificate.
if [ ! -f /data/nginx/dummycert.pem ] || [ ! -f /data/nginx/dummykey.pem ]
then
	echo "Generating dummy SSL certificate..."
	openssl req -new -newkey rsa:2048 -days 365000 -nodes -x509 -subj '/CN=*' -sha256 -keyout /data/nginx/dummykey.pem -out /data/nginx/dummycert.pem
	echo "Complete"
fi

# Handle IPV6 settings
/bin/handle-ipv6-setting /usr/local/openresty/nginx/conf/conf.d
/bin/handle-ipv6-setting /data/nginx

exec nginx
