name: spellcheck
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  spellcheck:
    name: spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v4
      - name: Check spelling
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: true
          skip: .git,.gitignore,de-lang.json,it-lang.json,showdown.min.js,jquery.min.js,xregexp-all.js
